# Generated by Django 5.1.4 on 2025-04-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("description",)},
        ),
    ]
