# Generated by Django 5.1.4 on 2025-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_remove_transaction_id_alter_transaction_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
